[package]
name = "habitat_core"
version = "0.0.0"
authors = ["Adam Jacob <adam@chef.io>", "Jamie Winsor <reset@chef.io>", "Fletcher Nichol <fnichol@chef.io>", "Joshua Timberman <joshua@chef.io>", "Dave Parfitt <dparfitt@chef.io>"]
workspace = "../../"

[dependencies]
errno = "*"
lazy_static = "*"
libarchive = "*"
libc = "*"
libsodium-sys = "*"
log = "*"
regex = "*"
rustc-serialize = "*"
sodiumoxide = "*"
time = "*"
toml = "*"
url = "*"

[target.'cfg(not(windows))'.dependencies]
users = "*"

[dev-dependencies]
tempdir = "*"

[dev-dependencies.hyper]
version = "*"
default-features = false

[features]
functional = []
