[package]
name = "habitat-sup-client"
version = "0.0.0"
edition = "2018"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
workspace = "../../"

[dependencies]
futures = "*"
habitat-sup-protocol = { path = "../sup-protocol", default-features = false }
habitat_common = { path = "../common" }
log = "*"
prost = "*"
termcolor = "*"
tokio = "*"
tokio-core = "*"
tokio-codec = "*"

[build-dependencies]
protoc = "1.4"
protoc-rust = "1.4"

