[package]
name = "habitat-sup-protocol"
version = "0.0.0"
authors = ["Jamie Winsor <reset@chef.io>"]
build = "./build.rs"
workspace = "../../"

[dependencies]
base64 = "*"
bytes = "*"
futures = "*"
habitat_core = { git = "https://github.com/habitat-sh/core.git" }
lazy_static = "*"
log = "*"
prost = "*"
prost-derive = "*"
rand = "*"
serde = "*"
serde_derive = "*"
tokio = "*"
tokio-io = "*"

[build-dependencies]
heck = "*"
prost = "*"
prost-build = "*"
prost-types = "*"
tempdir = "*"

[dev-dependencies]
toml = "*"
