[package]
name = "habitat_common"
version = "0.0.0"
authors = ["Adam Jacob <adam@chef.io>", "Jamie Winsor <reset@chef.io>", "Fletcher Nichol <fnichol@chef.io>", "Joshua Timberman <joshua@chef.io>", "Dave Parfitt <dparfitt@chef.io>"]
workspace = "../../"

[dependencies]
clippy = {version = "*", optional = true}
ansi_term = "*"
glob = "*"
hyper = "0.10"
libc = "*"
log = "*"
pbr = "*"
regex = "*"
tempdir = "*"
retry = "*"
term = "*"
time = "*"
toml = { version = "*", default-features = false }
uuid = { version = "*", features = ["v4"] }

[dependencies.habitat_core]
git = "https://github.com/habitat-sh/core.git"

[dependencies.habitat_api_client]
path = "../builder-api-client"

[target.'cfg(windows)'.dependencies]
winapi = { version = "*", features = ["consoleapi", "processenv"] }

[features]
default = []
functional = []
