[package]
name = "habitat-launcher"
version = "0.0.0"
authors = ["Jamie Winsor <reset@habitat.sh>"]
workspace = "../../"

[[bin]]
name = "hab-launch"
path = "src/main.rs"
doc = false

[dependencies]
ansi_term = "*"
env_logger = "*"
# JW TODO: core has external deps that we don't want, libarchive/libsodium. We should either
# put these things behind a feature flag so we can statically compile the launcher.
habitat_core = { git = "https://github.com/habitat-sh/core.git" }
habitat-launcher-protocol = { path = "../launcher-protocol" }
ipc-channel = { git = "https://github.com/habitat-sh/ipc-channel", branch = "hbt-windows" }
libc = "*"
log = "*"
protobuf = "1.5.1"
semver = "*"
time = "*"

[target.'cfg(windows)'.dependencies]
winapi =  { version = "*", features = ["tlhelp32"] }
