[package]
name = "habitat-launcher-protocol"
version = "0.0.0"
edition = "2018"
authors = ["Jamie Winsor <reset@habitat.sh>"]
build = "build.rs"
workspace = "../../"

[dependencies]
bytes = "*"
prost = "*"
prost-derive = "*"
serde = "*"
serde_derive = "*"

[build-dependencies]
prost-build = "*"
