[package]
name = "habitat-launcher-protocol"
version = "0.0.0"
edition = "2018"
authors = ["Jamie Winsor <reset@habitat.sh>"]
build = "build.rs"

[dependencies]
protobuf = "1.5.1"
serde = "*"
serde_derive = "*"

[build-dependencies]
pkg-config = "*"

[features]
protocols = []
