[package]
name = "habitat-eventsrv-protocol"
version = "0.0.0"
edition = "2018"
authors = [
  "Josh Black <raskchanky@gmail.com>",
  "Christopher Maier <cmaier@chef.io>",
  "Jamie Winsor <reset@habitat.sh>",
]
build = "build.rs"
workspace = "../../"

[dependencies]
protobuf = "1.5.1"
serde = "*"
serde_derive = "*"

[build-dependencies]
protoc = "1.4"
protoc-rust = "1.4"

[features]
default = ["protocols"]
protocols = []
